export default {
  "status": 1,
  "desc": null,
  "data": [
    {
      "imgUrl": "https://images-na.ssl-images-amazon.com/images/I/51BwlyiNsZL._SX466_.jpg",
      "productUrl": "https://www.amazon.com/dp/B00000JBNQ",
      "productName": "texas instruments ti-503 sv 503sv/fbl/2l1 standard function calculator",
      "brandName": "texas instruments",
      "bsrRanking": 20,
      "bsrCategory": "electronics>office electronics>calculators>basic",
      "generationTime": "2008-08-15 00:00:00.0",
      "shopName": "",
      "amazon": "no",
      "fba": "no",
      "price": 6.29,
      "grade": 0,
      "reviewCount": 250,
      "sellers": 56,
      "minPrice": 5,
      "listRanking": 0,
      "asin": "B00000JBNQ",
      "otherBsrRanking": '["17 in Electronics>Office Electronics>Calculators>Basic", "5,260 in  Office Products>Office Supplies"]',
      "collection": false
    },
    {
      "imgUrl": "https://images-na.ssl-images-amazon.com/images/I/71-fPcMX8NL._SY679_.jpg",
      "productUrl": "https://www.amazon.com/dp/B00000K135",
      "productName": "m231 1/2-inch black on white tape for p-touch labeler",
      "brandName": "brother",
      "bsrRanking": 20,
      "bsrCategory": "office products",
      "generationTime": "2004-07-07 00:00:00.0",
      "shopName": "",
      "amazon": "yes",
      "fba": "yes",
      "price": 8.99,
      "grade": 0,
      "reviewCount": 1050,
      "sellers": 97,
      "minPrice": 8,
      "listRanking": 0,
      "asin": "B00000K135",
      "otherBsrRanking": '["17 in Electronics>Office Electronics>Calculators>Basic", "5,260 in  Office Products>Office Supplies"]',
      "collection": false
    },
    {
      "imgUrl": "https://images-na.ssl-images-amazon.com/images/I/51nPtroEcwL._SY450_.jpg",
      "productUrl": "https://www.amazon.com/dp/B00001W0HC",
      "productName": "sony 4t160vf 160-minute vhs 4-brick",
      "brandName": "sony",
      "bsrRanking": 20,
      "bsrCategory": "electronics>accessories & supplies>camera & photo accessories>blank video media>vhs",
      "generationTime": "2001-10-10 00:00:00.0",
      "shopName": "malelo and company",
      "amazon": "no",
      "fba": "yes",
      "price": 38.99,
      "grade": 0,
      "reviewCount": 18,
      "sellers": 16,
      "minPrice": 36,
      "listRanking": 0,
      "asin": "B00001W0HC",
      "otherBsrRanking": '["16 in Electronics>Accessories & Supplies>Camera & Photo Accessories>Blank Video Media>VHS", "554 in Computers & Accessories>Computer Accessories>Blank Media"]',
      "collection": false
    },
    {
      "imgUrl": "https://images-na.ssl-images-amazon.com/images/I/812KJHV0B1L._SX425_.gif",
      "productUrl": "https://www.amazon.com/dp/B00001XE0L",
      "productName": "fujifilm protc30 vhs-c (2-pack) (discontinued by manufacturer)",
      "brandName": "fujifilm",
      "bsrRanking": 20,
      "bsrCategory": "electronics>accessories & supplies>camera & photo accessories>blank video media>vhs-c",
      "generationTime": "1999-11-20 00:00:00.0",
      "shopName": "jaxtradingpost",
      "amazon": "no",
      "fba": "yes",
      "price": 12.99,
      "grade": 0,
      "reviewCount": 10,
      "sellers": 4,
      "minPrice": 12,
      "listRanking": 0,
      "asin": "B00001XE0L",
      "otherBsrRanking": '["11 in Electronics>Accessories & Supplies>Camera & Photo Accessories>Blank Video Media>VHS-C", "792 in Computers & Accessories>Computer Accessories>Blank Media"]',
      "collection": false
    },
    {
      "imgUrl": "https://images-na.ssl-images-amazon.com/images/I/71lHqm7Jl8S._SX466_.jpg",
      "productUrl": "https://www.amazon.com/dp/B0000224EZ",
      "productName": "woodstock w1250 rosette cutterhead",
      "brandName": "woodstock",
      "bsrRanking": 20,
      "bsrCategory": "tools & home improvement",
      "generationTime": "2004-10-09 00:00:00.0",
      "shopName": "norfield industries",
      "amazon": "no",
      "fba": "no",
      "price": 33.75,
      "grade": 0,
      "reviewCount": 11,
      "sellers": 5,
      "minPrice": 29,
      "listRanking": 0,
      "asin": "B0000224EZ",
      "otherBsrRanking": '["460,192 in Tools & Home Improvement (See top 100)", "52 in Tools & Home Improvement>Power & Hand Tools>Power Tool Parts & Accessories>Shaper Accessories>Cutters", "937 in Tools & Home Improvement>Power & Hand Tools>Power Tool Parts & Accessories>Lathe Parts & Accessories"]',
      "collection": false
    },
    {
      "imgUrl": "https://images-na.ssl-images-amazon.com/images/I/71-fPcMX8NL._SY679_.jpg",
      "productUrl": "https://www.amazon.com/dp/B00000K135",
      "productName": "m231 1/2-inch black on white tape for p-touch labeler",
      "brandName": "brother",
      "bsrRanking": 20,
      "bsrCategory": "office products",
      "generationTime": "2004-07-07 00:00:00.0",
      "shopName": "",
      "amazon": "yes",
      "fba": "yes",
      "price": 8.99,
      "grade": 0,
      "reviewCount": 1050,
      "sellers": 97,
      "minPrice": 8,
      "listRanking": 0,
      "asin": "B00000K135",
      "otherBsrRanking": '["17 in Electronics>Office Electronics>Calculators>Basic", "5,260 in  Office Products>Office Supplies"]',
      "collection": false
    },
    {
      "imgUrl": "https://images-na.ssl-images-amazon.com/images/I/51nPtroEcwL._SY450_.jpg",
      "productUrl": "https://www.amazon.com/dp/B00001W0HC",
      "productName": "sony 4t160vf 160-minute vhs 4-brick",
      "brandName": "sony",
      "bsrRanking": 20,
      "bsrCategory": "electronics>accessories & supplies>camera & photo accessories>blank video media>vhs",
      "generationTime": "2001-10-10 00:00:00.0",
      "shopName": "malelo and company",
      "amazon": "no",
      "fba": "yes",
      "price": 38.99,
      "grade": 0,
      "reviewCount": 18,
      "sellers": 16,
      "minPrice": 36,
      "listRanking": 0,
      "asin": "B00001W0HC",
      "otherBsrRanking": '["16 in Electronics>Accessories & Supplies>Camera & Photo Accessories>Blank Video Media>VHS", "554 in Computers & Accessories>Computer Accessories>Blank Media"]',
      "collection": false
    },
    {
      "imgUrl": "https://images-na.ssl-images-amazon.com/images/I/812KJHV0B1L._SX425_.gif",
      "productUrl": "https://www.amazon.com/dp/B00001XE0L",
      "productName": "fujifilm protc30 vhs-c (2-pack) (discontinued by manufacturer)",
      "brandName": "fujifilm",
      "bsrRanking": 20,
      "bsrCategory": "electronics>accessories & supplies>camera & photo accessories>blank video media>vhs-c",
      "generationTime": "1999-11-20 00:00:00.0",
      "shopName": "jaxtradingpost",
      "amazon": "no",
      "fba": "yes",
      "price": 12.99,
      "grade": 0,
      "reviewCount": 10,
      "sellers": 4,
      "minPrice": 12,
      "listRanking": 0,
      "asin": "B00001XE0L",
      "otherBsrRanking": '["11 in Electronics>Accessories & Supplies>Camera & Photo Accessories>Blank Video Media>VHS-C", "792 in Computers & Accessories>Computer Accessories>Blank Media"]',
      "collection": false
    },
    {
      "imgUrl": "https://images-na.ssl-images-amazon.com/images/I/710DJTWBF2L.gif",
      "productUrl": "https://www.amazon.com/dp/B00001ZUNN",
      "productName": "nikon n70 slr camera (body only)",
      "brandName": "nikon",
      "bsrRanking": 20,
      "bsrCategory": "camera & photo",
      "generationTime": "1973-09-04 00:00:00.0",
      "shopName": "",
      "amazon": "no",
      "fba": "no",
      "price": 13,
      "grade": 0,
      "reviewCount": 22,
      "sellers": 10,
      "minPrice": 13,
      "listRanking": 0,
      "asin": "B00001ZUNN",
      "otherBsrRanking": '["25,445 in Camera & Photo (See Top 100 in Camera & Photo)", "64 in Electronics>Camera & Photo>Film Photography>Film Cameras>Point & Shoot Film Cameras", "109 in Electronics>Camera & Photo>Film Photography>Film Cameras>SLR Cameras"]',
      "collection": false
    },
    {
      "imgUrl": "https://images-na.ssl-images-amazon.com/images/I/71lHqm7Jl8S._SX466_.jpg",
      "productUrl": "https://www.amazon.com/dp/B0000224EZ",
      "productName": "woodstock w1250 rosette cutterhead",
      "brandName": "woodstock",
      "bsrRanking": 20,
      "bsrCategory": "tools & home improvement",
      "generationTime": "2004-10-09 00:00:00.0",
      "shopName": "norfield industries",
      "amazon": "no",
      "fba": "no",
      "price": 33.75,
      "grade": 0,
      "reviewCount": 11,
      "sellers": 5,
      "minPrice": 29,
      "listRanking": 0,
      "asin": "B0000224EZ",
      "otherBsrRanking": '["460,192 in Tools & Home Improvement (See top 100)", "52 in Tools & Home Improvement>Power & Hand Tools>Power Tool Parts & Accessories>Shaper Accessories>Cutters", "937 in Tools & Home Improvement>Power & Hand Tools>Power Tool Parts & Accessories>Lathe Parts & Accessories"]',
      "collection": false
    }
  ]
}
