export  default {
   columnsData:[
     {
       chinese:"产品图片",
       key:"imgUrl",
       sortable:false
     },
     {
       chinese:"产品链接",
       key:"productUrl",
       sortable:false
     },
     {
       chinese:"ASIN",
       key:"asin",
       sortable:false
     },
     {
       chinese:"产品名称",
       key:"productName",
       relation:"EQUAL",
       sortable:false
     },
     {
       chinese:"榜单排名",
       key:"listRanking",
       sortable:'custom'
     },
     {
       chinese:"品牌名",
       key:"brandName",
       sortable:false
     },
     {
       chinese:"大类目",
       key:"bsrCategory",
       sortable:false
     },
     {
       chinese:"BSR排名",
       key:"bsrRanking",
       sortable:'custom'
     },
     {
       chinese:"子类目及BSR排名",
       key:"otherBsrRanking",
       sortable:false
     },
     {
       chinese:"亚马逊自营",
       key:"amazon",
       sortable:false
     },
     {
       chinese:"店铺名",
       key:"shopName",
       sortable:false
     },
     {
       chinese:"上架时间",
       key:"generationTime",
       sortable:'custom'
     },
     {
       chinese:"FBA",
       key:"fba",
       sortable:false
     },
     {
       chinese:"售价",
       key:"price",
       sortable:'custom'
     },
     {
       chinese:"评论数",
       key:"reviewCount",
       sortable:'custom'
     },
     {
       chinese:"评分数",
       key:"grade",
       sortable:'custom'
     },
     {
       chinese:"跟卖卖家",
       key:"sellers",
       sortable:'custom'
     },
     {
       chinese:"跟售最低价",
       key:"minPrice",
       sortable:'custom'
     }
   ]
}
